name: dio_http_cache
description: http cache lib for Flutter dio like RxCache.It use sqflite as disk cache,and google/quiver-dart/LRU strategy as memory cache.
version: 0.3.2
homepage: https://github.com/MicheleOT/dio-http-cache

environment:
  sdk: ">=2.17.3 <3.0.0"

dependencies:
  crypto: ^3.0.1
  dio: ^5.0.0
  flutter:
    sdk: flutter
  json_serializable: ^6.2.0
  json_annotation: ^4.5.0
  path: ^1.8.0
  quiver: ^3.1.0
  hive: ^2.2.2
  path_provider: ^2.0.11

dev_dependencies:
  build_runner: ^2.1.10
  flutter_test:
    sdk: flutter

flutter:
  module:
    androidX: true
